name: release

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-wasi

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            target
            Cargo.lock
          key: cargo-dev--ubuntu-latest-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-dev--ubuntu-latest

      # Ensure that all components are compilable.
      - run: cargo test --color always --all

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm run prepack

      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
